# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 'dev'


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Setup AWS SAM CLI
        # You may pin to the exact commit or the version.
        # uses: aws-actions/setup-sam@8cbdb0241613f319ffe1c1b9f9d8f54ce772b5d3
        uses: aws-actions/setup-sam@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        
      - name: list api
        run: aws apigateway get-rest-api --rest-api-id ${{ secrets.REST_API_KEY }} 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: deploy rest api
        run: aws apigateway create-deployment --rest-api-id ${{ secrets.REST_API_KEY }} --stage-name dev --stage-description 'Development Stage' --description 'First deployment to the dev stage'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
          
  deploy-to-uat:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      environment: 'uat'
      env:
        token_id : 5ce4a89d-4d60-4248-ba8f-457f18cc2156
        organization : nousinfosystems
        swaggerhub_host : api.swaggerhub.com

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name : Publish version
          uses: fjogeleit/http-request-action@v1
          id: swaggereq
          with:
            url: 'https://${{env.swaggerhub_host}}/apis/${{env.organization}}/ncb-dontuse-api/1.0.0/settings/lifecycle?force=true'
            data: '{"published": true}'
            method: 'PUT'
            bearerToken: '${{env.token_id}}'
          if: github.ref == 'refs/heads/main'
        - name: Swaggerresponse
          run: echo ${{ steps.swaggereq.outputs.response }}
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Setup AWS SAM CLI
          # You may pin to the exact commit or the version.
          # uses: aws-actions/setup-sam@8cbdb0241613f319ffe1c1b9f9d8f54ce772b5d3
          uses: aws-actions/setup-sam@v2
          with:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: list api
          run: aws apigateway get-rest-api --rest-api-id ${{ secrets.REST_API_KEY }} 
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: deploy rest api
          run: aws apigateway create-deployment --rest-api-id ${{ secrets.REST_API_KEY }} --stage-name uat --stage-description 'Development Stage' --description 'First deployment to the uat stage'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            
  deploy-to-test:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      environment: 'test'


      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3



        - name: Setup AWS SAM CLI
          # You may pin to the exact commit or the version.
          # uses: aws-actions/setup-sam@8cbdb0241613f319ffe1c1b9f9d8f54ce772b5d3
          uses: aws-actions/setup-sam@v2
          with:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: list api
          run: aws apigateway get-rest-api --rest-api-id ${{ secrets.REST_API_KEY }} 
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: deploy rest api
          run: aws apigateway create-deployment --rest-api-id ${{ secrets.REST_API_KEY }} --stage-name test --stage-description 'test Stage' --description 'First deployment to the test stage'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            
  
          

          

          
          
        

        
       
         
        
        
