# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Setup AWS SAM CLI
        # You may pin to the exact commit or the version.
        # uses: aws-actions/setup-sam@8cbdb0241613f319ffe1c1b9f9d8f54ce772b5d3
        uses: aws-actions/setup-sam@v2
        
      - name: import api
        run: |
          aws apigateway import-rest-api --body ' openapi: "3.0.0"
info:
  version: 1.0.0
  title: ncb-accounts-api
  description: API to move the logs data from source to target

servers:
- url: http://ncb-accounts-api.us-e2.cloudhub.io/api
  description: API implementation in Mulesoft 


paths:
  /accounts/{accountid}/monthlystatements/move:
    post:
      tags:
        - Account Statements
      summary: Endpoint to move the monthly statements.
      description: Move the monthly statements from source to destination.
      operationId: movemonthlystatements
      parameters:
      
        - name: accountid
          in: path
          required: true
          schema:
            type: string
            example: "12352"
        - name: app_client_id
          in : header
          required: true
          schema:
            type: string
            example: "fhgf366739dsa897fd"    
        - name: monthandyear
          in: query
          required: true
          schema:
            type: string
            pattern: '^\d{2}-\d{4}$'
            example: "02-2022"
           
      responses:
        '200':
          description: Success Data Response
          content:
            application/json: 
              example:
                Message: 02-2022.txt has been copied to the target location 12345/02-2022.txt 
        "400":
          description: Error Response
          content:
            application/json:
              example:
                Message: Bad Request.
        "401":
          description: Error Response
          content:
            application/json:
              example:
                Message: Unauthorized.
        "404":
          description: Error Response
          content:
            application/json:
              example:
                Message: No file present in the source.                               
        "500":
          description: Error Response
          content:
            application/json:
              example:
                Message: Internal server error at the source.        
  /api/accounts/{accountid}:
    get:
      tags:
        - apilogs
      summary: Endpoint to move the logs data.
      description: to move the Logs data.
      operationId: getaccount-details
      parameters:
        - name: accountid
          in: path
          required: true
          schema:
            type: string
            example: "12352"
        - name: app_client_id
          in : header
          required: true
          schema:
            type: string
            example: "fhgf366739dsa897fd"     
      responses:
        "200":
          description: Success Data Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Error Response
          content:
            application/json:
              example:
                Message: Bad Request.
        "401":
          description: Error Response
          content:
            application/json:
              example:
                Message: Unauthorized.
        "404":
          description: Error Response
          content:
            application/json:
              example:
                Message: Account not found.
        "500":
          description: Error Response
          content:
            application/json:
              example:
                Message: Internal server error.



  /external/api:
    post:
      deprecated: true
      tags:
        - apilogs
      summary: Endpoint to make external api calls for logs data.
      description: to make external api calls for logs data.  
      operationId: callexternal-api
      responses:
        "200":
          description: Success Data Response
          content:
            application/json:
              example:
                             
components:
  schemas:
    Account:
      type: object
      properties:
        account:
          type: object
          properties:
            iban:
              type: string
              example: "DE27100777770209299700"
            bban:
              type: string
              example: "BARC12345612345678"
            pan:
              type: string
              example: "5409050000000000"  
            maskedPan:
              type: string
              example: "123456xxxxxx1234"
            msisdn:
              type: string
              example: "+49 170 1234567"  
            currency:
              type: string
              example: "EUR"  '

        
        env:
          AWS_ACCESS_KEY_ID: AKIA6OZ577OXFUZJ3UXI
          AWS_SECRET_ACCESS_KEY: OXR7xSMc+Klzxsh56z7qlVAi3kvVSLdiqro1+ZAH
          AWS_DEFAULT_REGION: 'us-east-1'
         
        
        
