# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Setup AWS SAM CLI
        # You may pin to the exact commit or the version.
        # uses: aws-actions/setup-sam@8cbdb0241613f319ffe1c1b9f9d8f54ce772b5d3
        uses: aws-actions/setup-sam@v2
        with:
          AWS_ACCESS_KEY_ID: AKIA6OZ577OXFUZJ3UXI
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: 'us-east-1'
        
      - name: list api
        run: aws apigateway get-rest-api --rest-api-id z2g6moe610 
        env:
          AWS_ACCESS_KEY_ID: AKIA6OZ577OXFUZJ3UXI
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: 'us-east-1'
          
      - name: deploy rest api
        run: aws apigateway create-deployment --rest-api-id z2g6moe610 --stage-name dev --stage-description 'Development Stage' --description 'First deployment to the dev stage'
        env:
          AWS_ACCESS_KEY_ID: AKIA6OZ577OXFUZJ3UXI
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: 'us-east-1'
          
          
        

        
       
         
        
        
